name: Vital Vialas Portfolio
author: Vital Vialas
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title

collections:
  projects:
    output: true

# permalink: /work/:title


title: Vital Vialas Portfolio
email: uveuve@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
